version: "3.7"

networks:
  esnet:

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    container_name: kibana
    restart: always
    environment:
    - ELASTICSEARCH_HOSTS=http://es01:9200
    ports: ["5601:5601"]
    depends_on: ["es01"]
    networks: ["esnet"]
